name: PyWPS
markdown: kramdown
highlighter: pygments
timezone: GMT
#baseurl: http://pywps.org
baseurl: http://geopython.github.io/pywps.org/
description: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium. PyWPS is written in Python.
keywords: PyWPS, WPS, OGC, processing
exclude: [README.md, setenv-ruby-gem, LICENSE, CNAME]
gems:
- jekyll-mentions
- jekyll-sitemap
- jekyll-feed
